# Generated by Django 4.2.5 on 2023-10-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("A", "ADMIN"),
                    ("C", "CASHIER"),
                    ("W", "WAITER"),
                    ("CH", "CHEF"),
                ],
                default="W",
                max_length=2,
            ),
        ),
    ]
