# Generated by Django 4.2.5 on 2023-09-21 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rms', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('CO', 'Cooking'), ('C', 'Completed'), ('CA', 'Cancelled')], default='P', max_length=2)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rms.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
